#!/usr/bin/env bash

SAVE_NAME="$(date +%Y-%b-%d_%H-%M-%S).png"
SAVE_DIR="$HOME/Pictures/Screenshots"

case $1 in
"all")
	grim "$SAVE_DIR/$SAVE_NAME"
	notify-send -a "Maim" -i "$SAVE_DIR/$SAVE_NAME" -u critical "Screenshot Saved" "Saved to $SAVE_DIR as $SAVE_NAME"
	;;
"copy")
	grim - | wl-copy
	notify-send -a "Maim" -u critical "Screenshot Copied" "Copied to Clipboard"
	;;
"select")
	grim -g "$(slurp)" "$SAVE_DIR/$SAVE_NAME"
	notify-send -a "Maim" -i "$SAVE_DIR/$SAVE_NAME" -u critical "Screenshot Saved" "Saved to $SAVE_DIR as $SAVE_NAME"
	;;
*) exit 1 ;;
esac
