#!/usr/bin/env bash

CURRENT_MODE=$(gsettings get org.gnome.desktop.interface color-scheme)

if [ "$CURRENT_MODE" = "'prefer-dark'" ]; then
	NEW_MODE="prefer-light"
	GTK_THEME="Adwaita"
	notify-send -a "Toggle Theme" -i "$HOME/.local/bin/scripts/assets/toggle_theme.png" -u low "Light Mode" "On"
else
	NEW_MODE="prefer-dark"
	GTK_THEME="Adwaita-dark"
	notify-send -a "Toggle Theme" -i "$HOME/.local/bin/scripts/assets/toggle_theme.png" -u low "Dark Mode" "On"
fi

gsettings set org.gnome.desktop.interface color-scheme "$NEW_MODE"
gsettings set org.gnome.desktop.interface gtk-theme "$GTK_THEME"
